### ISSUE TITLE
User created and deleted in web interface before cron job was run causing errors

### ISSUE THREAD

**Issue by ThRPctmylSgltwH** [friendica/docker#170]
I created and then deleted a user before the cron job was run. Now when I try to run the cron job I receive the following error where null seems to be the error.

root@71a3d6fea87b:/var/www/html# php bin/daemon.php start
Starting worker daemon.
Child process started with pid 935.
root@71a3d6fea87b:/var/www/html# 
Fatal error: Uncaught TypeError: Argument 1 passed to Friendica\Model\Item::storeForUserByUriId() must be of the type int, null given, called in /var/www/html/src/Worker/Notifier.php on line 540 and defined in /var/www/html/src/Model/Item.php:1365
Stack trace:
#0 /var/www/html/src/Worker/Notifier.php(540): Friendica\Model\Item::storeForUserByUriId(NULL, 2, Array, NULL)
#1 /var/www/html/src/Worker/Notifier.php(488): Friendica\Worker\Notifier::delivery('relocate', 3, 0, Array, Array, Array, false, false, Array, Array, Array)
#2 [internal function]: Friendica\Worker\Notifier::execute('relocate', 3)
#3 /var/www/html/src/Core/Worker.php(458): call_user_func_array('Friendica\\Worke...', Array)
#4 /var/www/html/src/Core/Worker.php(348): Friendica\Core\Worker::execFunction(Array, 'Notifier', Array, true)
#5 /var/www/html/src/Core/Worker.php(111): Friendica\Core\Worker::execute(Array)
#6 /var/www/html/bin/worker.php(83): Friendica\Core\Worker::processQueue(true)
#7 {main}
  thrown in /var/www/html/src/Model/Item.php on line 1365

The web interface still lists the queue as follows and I cannot remove the entries.

Administration - Inspect worker queue (5)
This page lists the currently queued worker jobs. These jobs are handled by the worker cronjob you've set up during install.

ID	Command	Job parameters	Created	Priority
7212	Notifier	relocate: 3	2021-07-14 08:57:54	20
7213	Notifier	mail: 1	2021-07-14 09:07:19	20
7214	Notifier	mail: 2	2021-07-14 09:08:01	20
7435	Notifier	mail: 5	2021-07-14 14:54:14	20
7438	Notifier	mail: 7	2021-07-14 14:57:39	20

How can I repair the database. Is there a command to rebuild or cleanup.

My database container is yobasystems/alpine-mariadb:10.4.17 so it does not have a command line interface.

/var/www/html/friendica.log contains the following but I replaced my email address with "xxx@hotmail.com" and the actual website name with yyy.com

2021-06-29T21:01:27Z index [ERROR]: PHPMailer error {&quot;email&quot;:&quot;{\&quot;fromName\&quot;:\&quot;Friendica Social Network\&quot;,\&quot;fromAddress\&quot;:\&quot;noreply@social.yyy.com\&quot;,\&quot;replyTo\&quot;:\&quot;noreply@social.yyy.com\&quot;,\&quot;toAddress\&quot;:\&quot;xxx@hotmail.com\&quot;,\&quot;subject\&quot;:\&quot;Password reset requested at Friendica Social Network\&quot;,\&quot;msgHtml\&quot;:\&quot;&lt;!DOCTYPE HTML PUBLIC \\\&quot;-\\\/\\\/W3C\\\/\\\/DTD HTML 4.01 Transitional \\\/\\\/EN\\\&quot;&gt;\\n&lt;html&gt;\\n&lt;head&gt;\\n\\t&lt;title&gt;Friendica Notification&lt;\\\/title&gt;\\n\\t&lt;meta http-equiv=\\\&quot;Content-Type\\\&quot; content=\\\&quot;text\\\/html;charset=utf-8\\\&quot; \\\/&gt;\\n&lt;\\\/head&gt;\\n&lt;body&gt;\\n\\t&lt;table style=\\\&quot;border:1px solid #ccc\\\&quot;&gt;\\n\\t&lt;tbody&gt;\\n\\t\\t&lt;tr&gt;\\n\\t\\t\\t&lt;td style=\\\&quot;background:#084769; color:#FFFFFF; font-weight:bold; font-family:'lucida grande', tahoma, verdana,arial, sans-serif; padding: 4px 8px; vertical-align: middle; font-size:16px; letter-spacing: -0.03em; text-align: left;\\\&quot;&gt;\\n\\t\\t\\t\\t&lt;img style=\\\&quot;width:32px;height:32px; float:left;\\\&quot; src=\\\&quot;https:\\\/\\\/social.yyy.com\\\/images\\\/friendica-32.png\\\&quot; alt=\\\&quot;Friendica Banner\\\&quot;&gt;\\n\\t\\t\\t\\t&lt;div style=\\\&quot;padding:7px; margin-left: 5px; float:left; font-size:18px;letter-spacing:1px;\\\&quot;&gt;Friendica&lt;\\\/div&gt;\\n\\t\\t\\t\\t&lt;div style=\\\&quot;clear: both;\\\&quot;&gt;&lt;\\\/div&gt;\\n\\t\\t\\t&lt;\\\/td&gt;\\n\\t\\t&lt;\\\/tr&gt;\\n\\t\\t&lt;tr&gt;\\n\\t\\t\\t&lt;td&gt;\\n\\t\\t\\t\\t&lt;table&gt;\\n\\t&lt;thead&gt;\\n\\t&lt;tr&gt;\\n\\t\\t&lt;td&gt;\\n\\t\\t\\t&lt;br&gt;\\nDear Pat,&lt;br&gt;\\n\\tA request was received at \\\&quot;Friendica Social Network\\\&quot; to reset your account password&lt;br&gt;\\nTo confirm this request, please select the verification link&lt;br&gt;\\nbelow or paste it into your web browser's address bar.&lt;br&gt;\\n&lt;br&gt;\\nIf you did NOT request this change, please DO NOT follow the link&lt;br&gt;\\nprovided; ignore or delete this email, as the request will expire shortly.&lt;br&gt;\\n&lt;br&gt;\\nYour password will not be changed unless we can verify that you&lt;br&gt;\\nissued this request.\\n\\t\\t&lt;\\\/td&gt;\\n\\t&lt;\\\/tr&gt;\\n\\t&lt;\\\/thead&gt;\\n\\t&lt;tbody&gt;\\n\\t\\t&lt;tr&gt;\\n\\t\\t\\t&lt;td style=\\\&quot;padding-right:22px;\\\&quot;&gt;\\n\\t\\t\\t\\tFollow this link soon to verify your identity:&lt;br&gt;&lt;br&gt;&lt;a href=\\\&quot;https:\\\/\\\/social.yyy.com\\\/lostpass\\\/dfc8396fddb232a67ee324d65881a6c4\\\&quot;&gt;https:\\\/\\\/social.yyy.com\\\/lostpass\\\/dfc8396fddb232a67ee324d65881a6c4&lt;\\\/a&gt;&lt;br&gt;&lt;br&gt;You will then receive a follow-up message containing the new password.&lt;br&gt;You may change that password from your account settings page after logging in.&lt;br&gt;&lt;br&gt;The login details are as follows:&lt;br&gt;&lt;br&gt;Site Location:\\t&lt;a href=\\\&quot;https:\\\/\\\/social.yyy.com\\\&quot;&gt;https:\\\/\\\/social.yyy.com&lt;\\\/a&gt;&lt;br&gt;Login Name:\\tpat\\n\\t\\t\\t&lt;\\\/td&gt;\\n\\t\\t&lt;\\\/tr&gt;\\n\\t&lt;\\\/tbody&gt;\\n\\t&lt;tfoot&gt;\\n\\t\\t&lt;tr&gt;\\n\\t\\t\\t&lt;td&gt;\\n\\t\\t\\t\\tthanks\\n\\t\\t\\t&lt;\\\/td&gt;\\n\\t\\t&lt;\\\/tr&gt;\\n\\t&lt;tr&gt;\\n\\t\\t&lt;td&gt;\\n\\t\\t\\tFriendica Social Network Administrator\\n\\t\\t&lt;\\\/td&gt;\\n\\t&lt;\\\/tr&gt;\\n\\t&lt;\\\/tfoot&gt;\\n&lt;\\\/table&gt;\\n\\n\\t\\t\\t&lt;\\\/td&gt;\\n\\t\\t&lt;\\\/tr&gt;\\n\\t&lt;\\\/tbody&gt;\\n\\t&lt;\\\/table&gt;\\n&lt;\\\/body&gt;\\n&lt;\\\/html&gt;\\n\&quot;,\&quot;msgText\&quot;:\&quot;\\nDear Pat,\\n\\tA request was received at \\\&quot;Friendica Social Network\\\&quot; to reset your account password\\nTo confirm this request, please select the verification link\\nbelow or paste it into your web browser's address bar.\\n\\nIf you did NOT request this change, please DO NOT follow the link\\nprovided; ignore or delete this email, as the request will expire shortly.\\n\\nYour password will not be changed unless we can verify that you\\nissued this request.\\n\\nFollow this link soon to verify your identity:\\n\\nhttps:\\\/\\\/social.yyy.com\\\/lostpass\\\/dfc8396fddb232a67ee324d65881a6c4\\n\\nYou will then receive a follow-up message containing the new password.\\nYou may change that password from your account settings page after logging in.\\n\\nThe login details are as follows:\\n\\nSite Location:\\thttps:\\\/\\\/social.yyy.com\\nLogin Name:\\tpat\\n\\nthanks\\nFriendica Social Network Administrator\\n\&quot;,\&quot;additionalMailHeader\&quot;:{\&quot;Precedence\&quot;:[\&quot;list\&quot;],\&quot;X-Friendica-Host\&quot;:[\&quot;social.yyy.com\&quot;],\&quot;X-Friendica-Platform\&quot;:[\&quot;Friendica\&quot;],\&quot;X-Friendica-Version\&quot;:[\&quot;2021.04\&quot;],\&quot;List-ID\&quot;:[\&quot;&lt;notification.social.yyy.com&gt;\&quot;],\&quot;List-Archive\&quot;:[\&quot;&lt;https:\\\/\\\/social.yyy.com\\\/notifications\\\/system&gt;\&quot;]},\&quot;toUid\&quot;:4}&quot;,&quot;ErrorInfo&quot;:&quot;Could not instantiate mail function.&quot;,&quot;exception&quot;:&quot;PHPMailer\\PHPMailer\\Exception: Could not instantiate mail function. in \/var\/www\/html\/addon\/phpmailer\/vendor\/phpmailer\/phpmailer\/src\/PHPMailer.php:1791\nStack trace:\n#0 \/var\/www\/html\/addon\/phpmailer\/vendor\/phpmailer\/phpmailer\/src\/PHPMailer.php(1589): PHPMailer\\PHPMailer\\PHPMailer-&gt;mailSend('Date: Tue, 29 J...', 'This is a multi...')\n#1 \/var\/www\/html\/addon\/phpmailer\/vendor\/phpmailer\/phpmailer\/src\/PHPMailer.php(1423): PHPMailer\\PHPMailer\\PHPMailer-&gt;postSend()\n#2 \/var\/www\/html\/addon\/phpmailer\/phpmailer.php(104): PHPMailer\\PHPMailer\\PHPMailer-&gt;send()\n#3 \/var\/www\/html\/src\/Core\/Hook.php(217): phpmailer_emailer_send_prepare(Object(Friendica\\App), Object(Friendica\\Object\\Email))\n#4 \/var\/www\/html\/src\/Core\/Hook.php(193): Friendica\\Core\\Hook::callSingle(Object(Friendica\\App), 'emailer_send_pr...', Array, Object(Friendica\\Object\\Email))\n#5 \/var\/www\/html\/src\/Util\/Emailer.php(131): Friendica\\Core\\Hook::callAll('emailer_send_pr...', Object(Friendica\\Object\\Email))\n#6 \/var\/www\/html\/mod\/lostpass.php(89): Friendica\\Util\\Emailer-&gt;send(Object(Friendica\\Object\\Email))\n#7 \/var\/www\/html\/src\/LegacyModule.php(90): lostpass_post(Object(Friendica\\App))\n#8 \/var\/www\/html\/src\/LegacyModule.php(69): Friendica\\LegacyModule::runModuleFunction('post', Array)\n#9 [internal function]: Friendica\\LegacyModule::post(Array)\n#10 \/var\/www\/html\/src\/App\/Module.php(281): call_user_func(Array, Array)\n#11 \/var\/www\/html\/src\/App.php(556): Friendica\\App\\Module-&gt;run(Object(Friendica\\Core\\L10n), Object(Friendica\\App\\BaseURL), Object(Friendica\\Util\\Logger\\StreamLogger), Object(Friendica\\Util\\Profiler), Array, Array)\n#12 \/var\/www\/html\/index.php(42): Friendica\\App-&gt;runFrontend(Object(Friendica\\App\\Module), Object(Friendica\\App\\Router), Object(Friendica\\Core\\PConfig\\JitPConfig), Object(Friendica\\Security\\Authentication), Object(Friendica\\App\\Page), 1625000486.1526)\n#13 {main}&quot;} - {&quot;file&quot;:&quot;phpmailer.php&quot;,&quot;line&quot;:108,&quot;function&quot;:&quot;phpmailer_emailer_send_prepare&quot;,&quot;uid&quot;:&quot;fbccaf&quot;,&quot;process_id&quot;:46}
2021-07-04T14:01:03Z index [ERROR]: PHPMailer error {&quot;email&quot;:&quot;{\&quot;fromName\&quot;:\&quot;Friendica Social Network\&quot;,\&quot;fromAddress\&quot;:\&quot;noreply@social.yyy.com\&quot;,\&quot;replyTo\&quot;:\&quot;noreply@social.yyy.com\&quot;,\&quot;toAddress\&quot;:\&quot;xxx@hotmail.com\&quot;,\&quot;subject\&quot;:\&quot;Password reset requested at Friendica Social Network\&quot;,\&quot;msgHtml\&quot;:\&quot;&lt;!DOCTYPE HTML PUBLIC \\\&quot;-\\\/\\\/W3C\\\/\\\/DTD HTML 4.01 Transitional \\\/\\\/EN\\\&quot;&gt;\\n&lt;html&gt;\\n&lt;head&gt;\\n\\t&lt;title&gt;Friendica Notification&lt;\\\/title&gt;\\n\\t&lt;meta http-equiv=\\\&quot;Content-Type\\\&quot; content=\\\&quot;text\\\/html;charset=utf-8\\\&quot; \\\/&gt;\\n&lt;\\\/head&gt;\\n&lt;body&gt;\\n\\t&lt;table style=\\\&quot;border:1px solid #ccc\\\&quot;&gt;\\n\\t&lt;tbody&gt;\\n\\t\\t&lt;tr&gt;\\n\\t\\t\\t&lt;td style=\\\&quot;background:#084769; color:#FFFFFF; font-weight:bold; font-family:'lucida grande', tahoma, verdana,arial, sans-serif; padding: 4px 8px; vertical-align: middle; font-size:16px; letter-spacing: -0.03em; text-align: left;\\\&quot;&gt;\\n\\t\\t\\t\\t&lt;img style=\\\&quot;width:32px;height:32px; float:left;\\\&quot; src=\\\&quot;https:\\\/\\\/social.yyy.com\\\/images\\\/friendica-32.png\\\&quot; alt=\\\&quot;Friendica Banner\\\&quot;&gt;\\n\\t\\t\\t\\t&lt;div style=\\\&quot;padding:7px; margin-left: 5px; float:left; font-size:18px;letter-spacing:1px;\\\&quot;&gt;Friendica&lt;\\\/div&gt;\\n\\t\\t\\t\\t&lt;div style=\\\&quot;clear: both;\\\&quot;&gt;&lt;\\\/div&gt;\\n\\t\\t\\t&lt;\\\/td&gt;\\n\\t\\t&lt;\\\/tr&gt;\\n\\t\\t&lt;tr&gt;\\n\\t\\t\\t&lt;td&gt;\\n\\t\\t\\t\\t&lt;table&gt;\\n\\t&lt;thead&gt;\\n\\t&lt;tr&gt;\\n\\t\\t&lt;td&gt;\\n\\t\\t\\t&lt;br&gt;\\nDear Pat Falcigno,&lt;br&gt;\\n\\tA request was received at \\\&quot;Friendica Social Network\\\&quot; to reset your account password&lt;br&gt;\\nTo confirm this request, please select the verification link&lt;br&gt;\\nbelow or paste it into your web browser's address bar.&lt;br&gt;\\n&lt;br&gt;\\nIf you did NOT request this change, please DO NOT follow the link&lt;br&gt;\\nprovided; ignore or delete this email, as the request will expire shortly.&lt;br&gt;\\n&lt;br&gt;\\nYour password will not be changed unless we can verify that you&lt;br&gt;\\nissued this request.\\n\\t\\t&lt;\\\/td&gt;\\n\\t&lt;\\\/tr&gt;\\n\\t&lt;\\\/thead&gt;\\n\\t&lt;tbody&gt;\\n\\t\\t&lt;tr&gt;\\n\\t\\t\\t&lt;td style=\\\&quot;padding-right:22px;\\\&quot;&gt;\\n\\t\\t\\t\\tFollow this link soon to verify your identity:&lt;br&gt;&lt;br&gt;&lt;a href=\\\&quot;https:\\\/\\\/social.yyy.com\\\/lostpass\\\/5f9bd21208a9570e779d2b305ba643e2\\\&quot;&gt;https:\\\/\\\/social.yyy.com\\\/lostpass\\\/5f9bd21208a9570e779d2b305ba643e2&lt;\\\/a&gt;&lt;br&gt;&lt;br&gt;You will then receive a follow-up message containing the new password.&lt;br&gt;You may change that password from your account settings page after logging in.&lt;br&gt;&lt;br&gt;The login details are as follows:&lt;br&gt;&lt;br&gt;Site Location:\\t&lt;a href=\\\&quot;https:\\\/\\\/social.yyy.com\\\&quot;&gt;https:\\\/\\\/social.yyy.com&lt;\\\/a&gt;&lt;br&gt;Login Name:\\tpat\\n\\t\\t\\t&lt;\\\/td&gt;\\n\\t\\t&lt;\\\/tr&gt;\\n\\t&lt;\\\/tbody&gt;\\n\\t&lt;tfoot&gt;\\n\\t\\t&lt;tr&gt;\\n\\t\\t\\t&lt;td&gt;\\n\\t\\t\\t\\tthanks\\n\\t\\t\\t&lt;\\\/td&gt;\\n\\t\\t&lt;\\\/tr&gt;\\n\\t&lt;tr&gt;\\n\\t\\t&lt;td&gt;\\n\\t\\t\\tFriendica Social Network Administrator\\n\\t\\t&lt;\\\/td&gt;\\n\\t&lt;\\\/tr&gt;\\n\\t&lt;\\\/tfoot&gt;\\n&lt;\\\/table&gt;\\n\\n\\t\\t\\t&lt;\\\/td&gt;\\n\\t\\t&lt;\\\/tr&gt;\\n\\t&lt;\\\/tbody&gt;\\n\\t&lt;\\\/table&gt;\\n&lt;\\\/body&gt;\\n&lt;\\\/html&gt;\\n\&quot;,\&quot;msgText\&quot;:\&quot;\\nDear Pat Falcigno,\\n\\tA request was received at \\\&quot;Friendica Social Network\\\&quot; to reset your account password\\nTo confirm this request, please select the verification link\\nbelow or paste it into your web browser's address bar.\\n\\nIf you did NOT request this change, please DO NOT follow the link\\nprovided; ignore or delete this email, as the request will expire shortly.\\n\\nYour password will not be changed unless we can verify that you\\nissued this request.\\n\\nFollow this link soon to verify your identity:\\n\\nhttps:\\\/\\\/social.yyy.com\\\/lostpass\\\/5f9bd21208a9570e779d2b305ba643e2\\n\\nYou will then receive a follow-up message containing the new password.\\nYou may change that password from your account settings page after logging in.\\n\\nThe login details are as follows:\\n\\nSite Location:\\thttps:\\\/\\\/social.yyy.com\\nLogin Name:\\tpat\\n\\nthanks\\nFriendica Social Network Administrator\\n\&quot;,\&quot;additionalMailHeader\&quot;:{\&quot;Precedence\&quot;:[\&quot;list\&quot;],\&quot;X-Friendica-Host\&quot;:[\&quot;social.yyy.com\&quot;],\&quot;X-Friendica-Platform\&quot;:[\&quot;Friendica\&quot;],\&quot;X-Friendica-Version\&quot;:[\&quot;2021.04\&quot;],\&quot;List-ID\&quot;:[\&quot;&lt;notification.social.yyy.com&gt;\&quot;],\&quot;List-Archive\&quot;:[\&quot;&lt;https:\\\/\\\/social.yyy.com\\\/notifications\\\/system&gt;\&quot;]},\&quot;toUid\&quot;:4}&quot;,&quot;ErrorInfo&quot;:&quot;Could not instantiate mail function.&quot;,&quot;exception&quot;:&quot;PHPMailer\\PHPMailer\\Exception: Could not instantiate mail function. in \/var\/www\/html\/addon\/phpmailer\/vendor\/phpmailer\/phpmailer\/src\/PHPMailer.php:1791\nStack trace:\n#0 \/var\/www\/html\/addon\/phpmailer\/vendor\/phpmailer\/phpmailer\/src\/PHPMailer.php(1589): PHPMailer\\PHPMailer\\PHPMailer-&gt;mailSend('Date: Sun, 4 Ju...', 'This is a multi...')\n#1 \/var\/www\/html\/addon\/phpmailer\/vendor\/phpmailer\/phpmailer\/src\/PHPMailer.php(1423): PHPMailer\\PHPMailer\\PHPMailer-&gt;postSend()\n#2 \/var\/www\/html\/addon\/phpmailer\/phpmailer.php(104): PHPMailer\\PHPMailer\\PHPMailer-&gt;send()\n#3 \/var\/www\/html\/src\/Core\/Hook.php(217): phpmailer_emailer_send_prepare(Object(Friendica\\App), Object(Friendica\\Object\\Email))\n#4 \/var\/www\/html\/src\/Core\/Hook.php(193): Friendica\\Core\\Hook::callSingle(Object(Friendica\\App), 'emailer_send_pr...', Array, Object(Friendica\\Object\\Email))\n#5 \/var\/www\/html\/src\/Util\/Emailer.php(131): Friendica\\Core\\Hook::callAll('emailer_send_pr...', Object(Friendica\\Object\\Email))\n#6 \/var\/www\/html\/mod\/lostpass.php(89): Friendica\\Util\\Emailer-&gt;send(Object(Friendica\\Object\\Email))\n#7 \/var\/www\/html\/src\/LegacyModule.php(90): lostpass_post(Object(Friendica\\App))\n#8 \/var\/www\/html\/src\/LegacyModule.php(69): Friendica\\LegacyModule::runModuleFunction('post', Array)\n#9 [internal function]: Friendica\\LegacyModule::post(Array)\n#10 \/var\/www\/html\/src\/App\/Module.php(281): call_user_func(Array, Array)\n#11 \/var\/www\/html\/src\/App.php(556): Friendica\\App\\Module-&gt;run(Object(Friendica\\Core\\L10n), Object(Friendica\\App\\BaseURL), Object(Friendica\\Util\\Logger\\StreamLogger), Object(Friendica\\Util\\Profiler), Array, Array)\n#12 \/var\/www\/html\/index.php(42): Friendica\\App-&gt;runFrontend(Object(Friendica\\App\\Module), Object(Friendica\\App\\Router), Object(Friendica\\Core\\PConfig\\JitPConfig), Object(Friendica\\Security\\Authentication), Object(Friendica\\App\\Page), 1625407261.5568)\n#13 {main}&quot;} - {&quot;file&quot;:&quot;phpmailer.php&quot;,&quot;line&quot;:108,&quot;function&quot;:&quot;phpmailer_emailer_send_prepare&quot;,&quot;uid&quot;:&quot;c6361d&quot;,&quot;process_id&quot;:46}
2021-07-05T19:04:43Z worker [ERROR]: compacting error {&quot;worker_id&quot;:&quot;9b33437&quot;,&quot;worker_cmd&quot;:&quot;UpdateGServer&quot;} - {&quot;file&quot;:&quot;JsonLD.php&quot;,&quot;line&quot;:153,&quot;function&quot;:&quot;compact&quot;,&quot;uid&quot;:&quot;b5cedd&quot;,&quot;process_id&quot;:269}

**Comment by MrPetovan** [comment]
Yes please.
